AspNetCoreIdentityApp.Web/Areas/Admin/ViewModels/RoleViewModel.cs
namespace AspNetCoreIdentityApp.Web.Areas.Admin.ViewModels
{
    public class RoleViewModel
    {
        public string Id { get; set; } = null!;
        public string Name { get; set; } = null!;
    }
}

AspNetCoreIdentityApp.Web/Areas/Admin/Controllers/RolesController.cs
using AspNetCoreIdentityApp.Core.Entities;
using AspNetCoreIdentityApp.Core.Entities.Services.MemberService;
using AspNetCoreIdentityApp.Core.Extensions.Identity.ModelState;
using AspNetCoreIdentityApp.Core.Services;
using AspNetCoreIdentityApp.Web.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace AspNetCoreIdentityApp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RolesController : Controller
    {
        private readonly IMemberService _memberService;

        public RolesController(IMemberService memberService)
        {
            _memberService = memberService;
        }

        public async Task<IActionResult> Index()
        {
            var roles = (await _memberService.GetRolesAsync()).Select(x => new RoleViewModel
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();

            return View(roles);
        }

        public async Task<IActionResult> Index2()
        {
            var roles = (await _memberService.GetRolesAsync()).Select(x => new RoleViewModel
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();

            return View(roles);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleCreateViewModel request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _memberService.CreateRoleAsync(request.Name);
            if (!result.Succeeded)
            {
                ModelState.AddModelStateErrors(result.Errors);
                return View();
            }
            TempData["SuccessMessage"] = "Role was created successfully.";
            return RedirectToAction(nameof(RolesController.Create));
        }

        public async Task<IActionResult> Update(string id)
        {
            (IdentityResult result, AppRole role) = await _memberService.GetRoleAsync(id);
            if (!result.Succeeded)
            {
                ModelState.AddModelStateErrors(result.Errors);
                return View();
            }
            return View(new RoleUpdateViewModel { Id = role.Id, Name = role.Name });
        }

        [HttpPost]
        public async Task<IActionResult> Update(RoleUpdateViewModel request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            (IdentityResult result, AppRole role) = await _memberService.UpdateRoleAsync(new RoleUpdate { Id = request.Id, Name = request.Name });
            if (!result.Succeeded)
            {
                ModelState.AddModelStateErrors(result.Errors);
                return View();
            }
            TempData["SuccessMessage"] = "Role was created successfully.";
            return View(role);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var result = await _memberService.DeleteRoleAsync(id);
            if (!result.Succeeded)
            {
                var errors = result.Errors.Select(error => error.Description).ToList().First();
                return BadRequest(new { message = "Role deletion failed.", errorDetail = errors });
            }
            TempData["SuccessMessage"] = "Role was deleted successfully.";

            return Ok(new { message = "Role deleted successfully."});
        }
    }
}

AspNetCoreIdentityApp.Web/Areas/Admin/Views/Roles/Create.cshtml
@model AspNetCoreIdentityApp.Web.Areas.Admin.ViewModels.RoleCreateViewModel

@{
    ViewData["Title"] = "RoleCreate";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

<div class="container">
    <div class="card" style="margin-top:5%;">
        <div class="d-flex justify-content-between">
            <h4 class="card-header">Role Create</h4>
            <a class="btn btn-primary" asp-area="Admin" asp-controller="Roles" asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    @if (@TempData["SuccessMessage"] is not null)
                    {
                        <div class="alert alert-dismissible alert-success">
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            <strong>Well done!</strong> @TempData["SuccessMessage"].
                        </div>
                    }
                    <div asp-validation-summary=ModelOnly class="alert alert-dismissible alert-danger">
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                    <form asp-area="Admin" asp-controller="Roles" asp-action="Create" method="post">
                        <label for="Name" class="form-label" asp-for="Name"></label>
                        <div class="mb-2">
                            <div class="d-flex align-items-center">
                                @*   <i class="fa-solid fa-pencil" style="margin-right:10px;"></i> *@
                                <input asp-for="Name" class="form-control" for="Name" aria-describedby="NameError" placeholder="Name">
                            </div>
                            <span class="text-danger" asp-validation-for="Name" style="margin-left:10%;"></span>
                        </div>
                        <div class="row">
                            <button type="submit" class="btn btn-primary"><i class="fa-solid fa-arrow-right-to-bracket"></i> Add </button>
                        </div>
                    </form>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <div class="row">
                            <p class="text-primary-emphasis"><i class="fa-solid fa-circle-exclamation"></i> Please exercise caution and obtain managerial approval when defining new roles.</p>
                            <p class="text-secondary-emphasis"><i class="fa-solid fa-circle-exclamation"></i> It's essential to obtain managerial approval before defining roles.</p>
                            <p class="text-danger-emphasis"><i class="fa-solid fa-circle-exclamation"></i> Care should be taken to avoid defining unnecessary roles.</p>
                            <p class="text-dark-emphasis"><i class="fa-solid fa-circle-exclamation"></i> Avoid defining a role that encompasses all permissions.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AspNetCoreIdentityApp.Web/Areas/Admin/Views/Roles/Index.cshtml
@model IEnumerable<AspNetCoreIdentityApp.Web.Areas.Admin.ViewModels.RoleViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script>
        function deleteRole(roleId) {
            fetch('@Url.Action("Delete", "Roles", new { area = "Admin" })', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                body: 'id=' + roleId
            }).then(response => {
                if (response.ok) {
                    return response.json();
                } else {
                    return response.json().then(errorData => {
                        console.log(errorData.message);
                        throw new Error(errorData.errorDetail);
                    });
                }
            }).then(data => {
                console.log(data.message); 
                var deletedRoleElement = document.getElementById('rolecomponent_' + roleId);
                if (deletedRoleElement) {
                    deletedRoleElement.remove();
                    $('#liveToast .toast-body').text(data.message);
                    toastFunction();
                }
            }).catch(error => {
                $('#liveToast .toast-body').text(error.message);
                toastFunction();        
            });
        }
     
        function toastFunction() {
           
            const toastLiveExample = document.getElementById('liveToast')
            const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastLiveExample)
            toastBootstrap.show();
        }
    </script>
}

<div class="container" id="asd">
    <div class="card" style="margin-top:5%;">
        <div class="d-flex justify-content-between">
            <h5 class="card-header"><strong>Roles</strong></h5>
            <a asp-controller="Roles" asp-action="Create" asp-area="Admin" class="btn btn-primary">Create</a>
        </div>
        <div class="card-body">
            <div class="row">
                @foreach (var role in Model)
                {
                    <div class="col-md-4" id="rolecomponent_@role.Id">
                        <div class="alert alert-primary">
                            <div class="d-flex justify-content-between">
                                <strong style="padding:4%">@role.Name</strong>
                                <div>
                                    <a asp-controller="Roles" asp-action="Update" asp-area="Admin" asp-route-id="@role.Id" class="btn btn-primary"><i class="fa-regular fa-pen-to-square"></i></a>
                                    @*   <a asp-route-id="@role.Id" data-role-id="@role.Id"  onclick="deleteRole('@role.Id')" class="btn btn-warning" id="deleterole"><i class="fa-solid fa-trash"></i></a> *@
                                    <button type="button" onclick="deleteRole('@role.Id')" class="btn btn-warning"><i class="fa-solid fa-trash"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <img src="~/images/updaterole.png" class="rounded me-2" alt="..." width="30px" height="30px">
            <strong class="me-auto">Information</strong>
            <small>1 mins ago</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
        </div>
    </div>
</div>

AspNetCoreIdentityApp.Web/Areas/Admin/Views/Roles/Update.cshtml
@model AspNetCoreIdentityApp.Web.Areas.Admin.ViewModels.RoleUpdateViewModel

@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

<div class="container">
    <div class="card" style="margin-top:5%;">
        <div class="d-flex justify-content-between">
            <h4 class="card-header">Role Update</h4>
            <a class="btn btn-primary" asp-area="Admin" asp-controller="Roles" asp-action="Index"><i class="fa-solid fa-arrow-left"></i></a>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    @if (@TempData["SuccessMessage"] is not null)
                    {
                        <div class="alert alert-dismissible alert-success">
                            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            <strong>Well done!</strong> @TempData["SuccessMessage"].
                        </div>
                    }
                    <div asp-validation-summary=ModelOnly class="alert alert-dismissible alert-danger">
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                    <form asp-area="Admin" asp-controller="Roles" asp-action="Update" method="post">
                        <input type="hidden" asp-for="Id"/>
                        <label for="Name" class="form-label" asp-for="Name"></label>
                        <div class="mb-2">
                            <div class="d-flex align-items-center">
                                <input asp-for="Name" class="form-control" for="Name" aria-describedby="NameError" placeholder="Name">
                            </div>
                            <span class="text-danger" asp-validation-for="Name" style="margin-left:10%;"></span>
                        </div>
                        <div class="row">
                            <button type="submit" class="btn btn-primary"><i class="fa-solid fa-arrow-right-to-bracket"></i> Add </button>
                        </div>
                    </form>
                </div>
                <div class="col-md-6">
                    <img src="~/images/updaterole.png" class="responsive-image" />
                </div>
            </div>
        </div>
    </div>
</div>